#!/bin/bash

#----- DECLARATIONS -----#

dir="$(dirname "$0")"

FAVS="$dir/data/favourites.list"

# INSTALL APPLICATIONS
function favourites {
# Install Favourite Applications
echo ''
echo 'Installing selected favourite applications...'
echo ''
echo 'Current package list:'
echo ''
for package in $(cat $FAVS)
do
echo -e '\t'$package
done
echo ''
show_info 'Proceed? (Y)es, (N)o : ' && read REPLY
echo ''
case $REPLY in
# Positive action
[Yy]* ) 
    show_info 'Requires root privileges:'

    sudo yum localinstall --nogpgcheck https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm -y
    sudo yum-config-manager --add-repo=http://negativo17.org/repos/fedora-flash-plugin.repo -y
    sudo yum-config-manager --add-repo=http://negativo17.org/repos/fedora-rar.repo -y
    sudo yum-config-manager --add-repo=http://negativo17.org/repos/fedora-skype.repo -y
    sudo yum-config-manager --add-repo=http://negativo17.org/repos/fedora-spotify.repo -y
    sudo yum-config-manager --add-repo=http://negativo17.org/repos/fedora-cdrtools.repo -y



    # Feel free to change the contents of 'favourites.list' to whatever suits your preferences.
    sudo yum install -y $(cat $FAVS)
    show_success 'Done.'
    main
    ;;
# Negative action
[Nn]* )
    clear && main
    ;;
# Error
* )
    clear && show_error '\aSorry, try again.'
    favourites
    ;;
esac
}
