#!/bin/bash

# SYSTEM UPGRADE
function upgrade {
# Perform system upgrade
echo ''
show_info 'Proceed with system upgrade and install of xfce? (Y)es, (N)o : ' 
read REPLY
echo ''
case $REPLY in
# Positive action
[Yy]* )
    # Update repository information
    echo 'Updating repository information...'
    show_info 'Requires root privileges:'
    sudo yum update -y
    sudo yum localinstall --nogpgcheck http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-21.noarch.rpm -y
    sudo yum localinstall --nogpgcheck http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-21.noarch.rpm -y
    sudo yum install yum-plugin-fastestmirror -y
    sudo yum update -y
    sudo yum install @xfce-desktop -y
    show_success 'Done - rebooting... When you login, choose xfce-session from the settings in the login prompt'
    sudo reboot -p
    main
    ;;
# Negative action
[Nn]* )
    clear && main
    ;;
# Error
* )
    clear && show_error '\aSorry, try again.'
    upgrade
    ;;
esac
}